<?php

/** @var \Corrivate\ComposerDashboard\Block\Adminhtml\Email\Advisories $block
 */

use Corrivate\ComposerDashboard\Model\Value\AuditIssue;

?>

<?php foreach ($block->getAdvisories() as $advisory): ?>
    <tr style="font-size:14px;">
        <td><?= $advisory->package ?></td>
        <td><?= $advisory->cve ?></td>
        <?php if($advisory->severity >= AuditIssue::SEVERITY_MEDIUM): ?>
            <td><?= AuditIssue::SEVERITY_LABELS[$advisory->severity] ?></td>
        <?php else: ?>
            <td><b style="color:red"><?= AuditIssue::SEVERITY_LABELS[$advisory->severity] ?></b></td>
        <?php endif; ?>

    </tr>
<?php endforeach; ?>
