<?php
/** @var \Magento\Backend\Block\Template $block */
?>

<div style="max-width: 60rem;">
    <p>
        These are your installed packages. <b style="color:blue">Direct</b> packages are specified by your <code>composer.json</code>.
    </p>
    <p>
        Packages with <b style="color:red">Update Possible</b> have much newer versions available. Updates may contain
        improvements, but always check for breaking changes.
    </p>
    <p>
        The <b>latest version</b> listed is what you have access to; if you use a third-party vendor, ensure your
        subscription is up to date for newer releases.</p>
</div>
