<?php

/** @var \Corrivate\ComposerDashboard\Block\Email\Outdated $block */
/** @var \Magento\Framework\Escaper $escaper */

use Corrivate\ComposerDashboard\Model\Value\InstalledPackage;

?>

<?php foreach ($block->getOutdated() as $package): ?>
    <tr>
        <td><?= $package->package ?></td>
        <td><?= $package->version ?></td>
        <td><?= $package->latest ?></td>
        <td><?= InstalledPackage::SEMVER_LABELS[$package->semver_status] ?? 'unknown' ?></td>
        <?php if($package->abandoned): ?>
            <td><b style="color:red">abandoned</b></td>
        <?php else: ?>
            <td></td>
        <?php endif; ?>

    </tr>
<?php endforeach; ?>
