<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */


$class = match($block->getValue()) {
    'up-to-date' => 'composer-badge--ok',
    'semver-safe-update' => 'composer-badge--warning',
    'update-possible' => 'composer-badge--danger',
    default => 'composer-badge--danger'
};
?>

<span class="composer-badge <?= $class ?>"><?= $escaper->escapeHtml($block->getValue())?></span>
